site_name: CopyAId.it
site_url: https://copyaid.it/
repo_name: gitlab<br>castedo/copyaid
repo_url: https://gitlab.com/castedo/copyaid
edit_uri: -/edit/copyaid.it/docs
theme:
  name: material
  custom_dir: theme
  features:
    - content.action.edit
    - content.code.copy
    - toc.integrate
    - navigation.footer
    - navigation.top
    - navigation.tracking
extra_css:
  - style/extra.css
markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - md_in_html
nav:
  - Home: index.md
  - Get Started: start.md
  - Hot Copyediting: hot.md
  - Reference:
    - Configuration: config.md
    - Request Settings: requests.md
  - How-To Guides:
    - howto/notvim.md
  - About: about.md
extra:
  analytics:
    provider: google
    property: G-XVLJFB05DV
  generator: false
copyright: '<a href="/about/">About</a>'
watch:
  - docs
  - theme
